name: dds_thinbox # Replace this name with your image name
id: dds_thinbox # Replace this ID with your image ID
stages:
- id: build
  base: ghcr.io/vanilla-os/desktop:main # Optionally, Replace this image URL with a different one i.e. nvidia:main, etc
  singlelayer: false
  labels:
    maintainer: self-maintained # Optionally, Replace this with your name
  args:
    DEBIAN_FRONTEND: noninteractive # Set the image environment as non-interactive
  
  # Commands to run first before building the modules
  runs:
    commands:
      - echo 'APT::Install-Recommends "1";' > /etc/apt/apt.conf.d/01norecommends

  modules:
  - name: init-setup
    type: shell
    commands:
    - lpkg --unlock
    - apt-get update
    
  # Put your custom actions below this comment
    
  - name: dds-setup_01
    type: shell
    commands:
    - wget -qO- https://workspaces-client-linux-public-key.s3-us-west-2.amazonaws.com/ADB332E7.asc >> /etc/apt/trusted.gpg.d/myrepo.asc
    - "[ ! -f /etc/apt/ADB332E7.asc ] || mv /etc/apt/ADB332E7.asc /etc/apt/trusted.gpg.d"
    - echo deb [arch=amd64] https://d3nt0h4h6pmmc4.cloudfront.net/ubuntu jammy main >> /etc/apt/sources.list.d/amazon-workspaces-clients.list   
    - curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
    - install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/
    - install -o root -g root -m 644 microsoft.gpg /usr/share/keyrings/
    - echo "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge-dev.list
    - echo "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft.gpg] https://packages.microsoft.com/ubuntu/22.04/prod jammy main" > /etc/apt/sources.list.d/microsoft-ubuntu-jammy-prod.list
    - echo "deb http://ftp.us.debian.org/debian bookworm main" >> /etc/apt/sources.list.d/debian-bookworm-prod.list
    - rm microsoft.gpg

  - name: dds-setup_01b
    type: shell
    commands:    
    - apt-get update
    #- apt-get install -y gnome-control-center
    #- apt-get install -y libjavascriptcoregtk-4.0-18
    #- apt-get install -y libwebkit2gtk-4.0-37
    #- apt-get install -y msalsdk-dbusclient
    #- apt-get install -y libcrack2
    #- apt-get install -y libcurl4
    - apt-get install -y libpam-pwquality-common
    - apt-get install -y libpwquality-common
    - apt-get install -y libpwquality1
    - apt-get install -y cracklib-runtime
    - apt-get install -y gnome-user-share
    - apt-get install -y gnome-keyring
    - apt-get install -y curl
    - apt-get install -y fastfetch
    
  - name: dds-setup_02
    type: shell
    commands:
    - chmod +x /var/tmp/ms_installs.sh
    - chmod +x /var/tmp/ws_install.sh
    #- bash /var/tmp/ms_installs.sh
    #- bash /var/tmp/ws_install.sh


#  - name: dds-setup_02
#    type: shell
#    commands:    
#    - chmod +x var/tmp/ddsinstalls_01.sh
#    - chmod +x var/tmp/ddsinstalls_02.sh
#    - chmod +x var/tmp/ddsinstalls_03.sh
    
#  - name: dds-setup_03
#    type: shell
#    commands:    
#    - bash var/tmp/ddsinstalls_01.sh
    
#  - name: dds-setup_03
#    type: shell
#    commands:    
#    - bash var/tmp/ddsinstalls_02.sh
    
#  - name: dds-setup_03
#    type: shell
#    commands:    
#    - bash var/tmp/ddsinstalls_03.sh

#  - name: my-deb
#    type: dpkg
#    source:
#      paths:
#        - "./var/tmp/new_workspacesclient_jammy_amd64.deb"


#  - name: dds-setup-microsoft-sources
#    type: shell    

  # Put your custom actions before this comment

  - name: set-image-name-abroot
    type: includes
    includes:
      - modules/80-set-image-abroot-config.yml

  - name: cleanup
    type: shell
    commands:
    - apt-get autoremove -y
    - apt-get clean
    - lpkg --lock

  - name: fsguard
    type: fsguard
    CustomFsGuard: false
    FsGuardLocation: "/usr/sbin/FsGuard"
    GenerateKey: true
    FilelistPaths: ["/usr/bin"]
    modules:
      - name: remove-prev-fsguard
        type: shell
        commands:
          - rm -rf /FsGuard 
          - rm -f ./minisign.pub ./minisign.key 
          - chmod +x /usr/sbin/init

  - name: cleanup2
    type: shell
    commands:
      - rm -rf /tmp/*
      - rm -rf /var/tmp/*
      - rm -rf /sources
